import { invoke } from "@tauri-apps/api/core";
import { z } from "zod";
import {
  ChannelReleaseSchema,
  UpdateChannelSchema,
  UpdateManifestSchema,
} from "@src/stores/settingsStore.ts";

// Wire types for the toolkit binary (`gnosis_vpn-update`), which the Rust side
// spawns for the installed package version and for update checks
// (src-tauri/src/toolkit.rs). The binary is the source of truth for both; the
// client library is no longer consulted. Fixtures for these schemas are
// generated by `cargo test --test serialize_fixtures` — see toolkit.test.ts.

// Rejection strings the Rust side returns when the binary cannot be used. The
// Updates tab turns them into an explanation rather than an error.
export const TOOLKIT_MISSING = "ToolkitMissing";
export const TOOLKIT_TOO_OLD = "ToolkitTooOld";

export const ToolkitInfoSchema = z.object({
  // The updater's own version.
  version: z.string(),
  // The installed client package, read from /etc/gnosisvpn/version.txt; null
  // when that file is missing.
  package_version: z.string().nullable(),
});
export type ToolkitInfo = z.infer<typeof ToolkitInfoSchema>;

// The decision a `check-update` reached, `kind`-tagged by the Rust bridge the
// same way InstallStatus is. Three of these never come through `checkUpdate`
// — the Rust command turns VpnNotConnected, IntegrityError and Error into
// rejections so the existing modal and background-check flows keep working —
// but the schema names them so a fixture or a future caller can.
export const CheckOutcomeSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("UpToDate"), current: z.string() }),
  z.object({
    kind: z.literal("Available"),
    current: z.string(),
    release: ChannelReleaseSchema,
  }),
  z.object({
    kind: z.literal("NoReleaseForChannel"),
    channel: UpdateChannelSchema,
  }),
  z.object({ kind: z.literal("VpnNotConnected") }),
  z.object({ kind: z.literal("IntegrityError"), error: z.string() }),
  z.object({ kind: z.literal("Error"), error: z.string() }),
]);
export type CheckOutcome = z.infer<typeof CheckOutcomeSchema>;

export const CheckResultSchema = z.object({
  // The channel that was checked: the one asked for, or the one the binary
  // inferred from the installed version.
  channel: UpdateChannelSchema,
  outcome: CheckOutcomeSchema,
  // Both channel entries exactly as fetched. Null only on outcomes that never
  // got a manifest, in which case the stored one is left alone.
  manifest: UpdateManifestSchema.nullable(),
});
export type CheckResult = z.infer<typeof CheckResultSchema>;

// Rejects with "VpnNotConnected" when the binary refused without the tunnel
// (skipVpn maps to its --force), with TOOLKIT_MISSING / TOOLKIT_TOO_OLD when
// it cannot be used, or with the binary's own error text.
export async function checkUpdate(skipVpn: boolean): Promise<CheckResult> {
  const raw = await invoke<unknown>("check_update", { skipVpn });
  return CheckResultSchema.parse(raw);
}

// Rejects with TOOLKIT_MISSING / TOOLKIT_TOO_OLD.
export async function getToolkitInfo(): Promise<ToolkitInfo> {
  const raw = await invoke<unknown>("get_toolkit_version");
  return ToolkitInfoSchema.parse(raw);
}
