import { describe, expect, it } from "vitest";

import { InstallStatusSchema } from "./updateInstall.ts";

// Fixtures are generated by `cargo test --test serialize_fixtures` in
// src-tauri from the real serde output of update_install::InstallStatus.
// When the Rust type changes, re-run that test to regenerate; if this file
// then fails, update InstallStatusSchema to match the new wire format.
import checking from "./fixtures/install_status_checking.json";
import downloading from "./fixtures/install_status_downloading.json";
import installing from "./fixtures/install_status_installing.json";
import completed from "./fixtures/install_status_completed.json";
import failed from "./fixtures/install_status_failed.json";

describe("InstallStatusSchema fixtures", () => {
  it("parses every phase fixture", () => {
    for (const fixture of [checking, downloading, installing]) {
      const parsed = InstallStatusSchema.safeParse(fixture);
      expect(parsed.success).toBe(true);
    }
  });

  it("parses the terminal fixtures with payloads", () => {
    const done = InstallStatusSchema.safeParse(completed);
    expect(done.success).toBe(true);
    if (done.success && done.data.kind === "Completed") {
      expect(done.data.new_version).toBe("0.78.0");
    }

    const fail = InstallStatusSchema.safeParse(failed);
    expect(fail.success).toBe(true);
    if (fail.success && fail.data.kind === "Failed") {
      expect(fail.data.stage).toBe("Download");
      expect(fail.data.error).toBe("connection reset");
    }
  });

  it("rejects unknown kinds and missing payload fields", () => {
    expect(InstallStatusSchema.safeParse({ kind: "Rebooting" }).success).toBe(
      false,
    );
    expect(InstallStatusSchema.safeParse({ kind: "Completed" }).success).toBe(
      false,
    );
    expect(InstallStatusSchema.safeParse("Downloading").success).toBe(false);
  });
});
