import { invoke } from "@tauri-apps/api/core";
import { z } from "zod";
import { type UpdateChannel } from "@src/stores/settingsStore.ts";

// Wire types for the `install_update` flow (src-tauri/src/update_install.rs).
// The Rust side runs the bundled gnosis_vpn-update binary (macOS-only) and
// broadcasts each progress step as an `update-install-status` event; the last
// status is also queryable via `get_install_status` so a remounting Updates
// tab can catch up mid-install.
// Fixtures for this schema are generated by
// `cargo test --test serialize_fixtures` — see updateInstall.test.ts.

export const UPDATE_INSTALL_STATUS_EVENT = "update-install-status";

export const InstallStatusSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("Checking") }),
  z.object({ kind: z.literal("Downloading") }),
  z.object({ kind: z.literal("Installing") }),
  z.object({ kind: z.literal("Completed"), new_version: z.string() }),
  z.object({ kind: z.literal("Failed"), stage: z.string(), error: z.string() }),
]);
export type InstallStatus = z.infer<typeof InstallStatusSchema>;

// Starts the updater; resolves once it is spawned. Progress and the outcome
// arrive via UPDATE_INSTALL_STATUS_EVENT. Rejects with "InstallInProgress",
// "UnsupportedPlatform", "InvalidChannel" or a spawn error.
export function installUpdate(
  channel: UpdateChannel,
  force: boolean,
): Promise<void> {
  return invoke<void>("install_update", { channel, force });
}

export async function getInstallStatus(): Promise<InstallStatus | null> {
  const raw = await invoke<unknown>("get_install_status");
  if (raw == null) return null;
  const parsed = InstallStatusSchema.safeParse(raw);
  return parsed.success ? parsed.data : null;
}
