import { describe, expect, it } from "vitest";
import {
  BalanceResponseSchema,
  ConnectResponseSchema,
  DestinationSchema,
  DisconnectResponseSchema,
  ProbeResponseSchema,
  QuickProbeResponseSchema,
  ServiceInfoSchema,
  StatusResponseSchema,
  UnprobeResponseSchema,
} from "./vpnService.ts";

// Fixtures are generated by `cargo test --test serialize_fixtures` in src-tauri.
// When library types change serde output, re-run that test to regenerate these files.
// If vitest then fails, update the Zod schemas to match the new wire format.
import statusNotRunning from "./fixtures/status_not_running.json";
import statusShutdown from "./fixtures/status_shutdown.json";
import statusWarmup from "./fixtures/status_warmup.json";
import statusRunning from "./fixtures/status_running.json";
import statusPreparingSafe from "./fixtures/status_preparing_safe.json";
import statusPreparingSafeWithRecommendation from "./fixtures/status_preparing_safe_with_recommendation.json";
import statusDeployingSafe from "./fixtures/status_deploying_safe.json";
import statusRestarting from "./fixtures/status_restarting.json";
import statusWithConnections from "./fixtures/status_with_connections.json";
import statusReconnectWaiting from "./fixtures/status_reconnect_waiting.json";
import statusRouteHealthVariants from "./fixtures/status_route_health_variants.json";
import statusProbeOpening from "./fixtures/status_probe_opening.json";
import connectNotFound from "./fixtures/connect_destination_not_found.json";
import connectConnecting from "./fixtures/connect_connecting.json";
import connectAlreadyConnected from "./fixtures/connect_already_connected.json";
import connectWaiting from "./fixtures/connect_waiting.json";
import connectUnable from "./fixtures/connect_unable.json";
import connectAmbiguous from "./fixtures/connect_ambiguous.json";
import disconnectNotConnected from "./fixtures/disconnect_not_connected.json";
import disconnectDisconnecting from "./fixtures/disconnect_disconnecting.json";
import probeProbing from "./fixtures/probe_probing.json";
import probeReplaced from "./fixtures/probe_replaced.json";
import probeAlreadyProbing from "./fixtures/probe_already_probing.json";
import probeUnable from "./fixtures/probe_unable.json";
import probeNotReady from "./fixtures/probe_not_ready.json";
import probeNotFound from "./fixtures/probe_destination_not_found.json";
import probeAmbiguous from "./fixtures/probe_ambiguous.json";
import unprobeClosing from "./fixtures/unprobe_closing.json";
import unprobeInUse from "./fixtures/unprobe_in_use.json";
import unprobeNotProbing from "./fixtures/unprobe_not_probing.json";
import quickProbeChecking from "./fixtures/quick_probe_checking.json";
import quickProbeUnable from "./fixtures/quick_probe_unable.json";
import quickProbeAlreadyProbing from "./fixtures/quick_probe_already_probing.json";
import quickProbeAlreadyChecking from "./fixtures/quick_probe_already_checking.json";
import quickProbeNotReady from "./fixtures/quick_probe_not_ready.json";
import quickProbeNotFound from "./fixtures/quick_probe_destination_not_found.json";
import quickProbeAmbiguous from "./fixtures/quick_probe_ambiguous.json";
import balanceResponse from "./fixtures/balance_response.json";
import balanceResponseWithIssues from "./fixtures/balance_response_with_issues.json";
import balanceResponseWithCapacity from "./fixtures/balance_response_with_capacity.json";
import serviceInfo from "./fixtures/service_info.json";

describe("StatusResponseSchema", () => {
  it("parses NotRunning run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusNotRunning).success).toBe(true);
  });

  it("parses Shutdown run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusShutdown).success).toBe(true);
  });

  it("parses Warmup run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusWarmup).success).toBe(true);
  });

  it("parses Running run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusRunning).success).toBe(true);
  });

  it("parses PreparingSafe run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusPreparingSafe).success).toBe(
      true,
    );
  });

  it("parses PreparingSafe run_mode with balance_recommendation", () => {
    const result = StatusResponseSchema.safeParse(
      statusPreparingSafeWithRecommendation,
    );
    expect(result.success).toBe(true);
    if (!result.success) return;
    const mode = result.data.run_mode;
    expect(typeof mode).toBe("object");
    expect("PreparingSafe" in (mode as object)).toBe(true);
    const ps = (mode as {
      PreparingSafe: {
        node_xdai: bigint;
        node_wxhopr: bigint;
        balance_recommendation: { wxhopr: bigint; xdai: bigint } | null;
      };
    }).PreparingSafe;
    expect(typeof ps.node_xdai).toBe("bigint");
    expect(typeof ps.node_wxhopr).toBe("bigint");
    expect(ps.balance_recommendation).not.toBeNull();
    expect(typeof ps.balance_recommendation!.wxhopr).toBe("bigint");
    expect(typeof ps.balance_recommendation!.xdai).toBe("bigint");
  });

  it("parses DeployingSafe run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusDeployingSafe).success).toBe(
      true,
    );
  });

  it("parses Restarting run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusRestarting).success).toBe(true);
  });

  it("parses ConnectedInfo, connection phases and a ready probe", () => {
    const parsed = StatusResponseSchema.safeParse(statusWithConnections);
    expect(parsed.success).toBe(true);
    expect(parsed.data?.connected?.tunnel_ping_rtt).toBe(12);
    expect(parsed.data?.probe?.state.state).toBe("Ready");
    expect(parsed.data?.probe?.load?.slots.available).toBe(10);
  });

  it("parses a probe session with no results yet", () => {
    const parsed = StatusResponseSchema.safeParse(statusProbeOpening);
    expect(parsed.success).toBe(true);
    expect(parsed.data?.probe?.state.state).toBe("Opening");
    expect(parsed.data?.probe?.versions).toBe(null);
  });

  it("parses all RouteHealthState, RouteWalk and QuickProbeState variants", () => {
    const parsed = StatusResponseSchema.safeParse(statusRouteHealthVariants);
    expect(parsed.success).toBe(true);
    const health = parsed.data?.destinations.map((d) => d.route_health) ?? [];
    expect(health[0]?.walk?.found).toBe("Paths");
    expect(health[0]?.quick_probe?.state).toBe("Checked");
    expect(health[2]?.state.state).toBe("NotRoutable");
    expect(health[2]?.last_error).toBe("walk timed out");
    expect(health[5]?.quick_probe?.state).toBe("Failed");
    expect(health[6]).toBe(null);
  });

  it("parses a reconnect reported without a phase", () => {
    const parsed = StatusResponseSchema.safeParse(statusReconnectWaiting);
    expect(parsed.success).toBe(true);
    expect(parsed.data?.reconnecting?.phase).toBe(null);
  });
});

describe("ConnectResponseSchema", () => {
  it("parses DestinationNotFound", () => {
    expect(ConnectResponseSchema.safeParse(connectNotFound).success).toBe(true);
  });

  it("parses Connecting", () => {
    expect(ConnectResponseSchema.safeParse(connectConnecting).success).toBe(
      true,
    );
  });

  it("parses AlreadyConnected", () => {
    expect(ConnectResponseSchema.safeParse(connectAlreadyConnected).success)
      .toBe(
        true,
      );
  });

  it("parses WaitingToConnect", () => {
    expect(ConnectResponseSchema.safeParse(connectWaiting).success).toBe(true);
  });

  it("parses UnableToConnect", () => {
    expect(ConnectResponseSchema.safeParse(connectUnable).success).toBe(true);
  });

  it("parses DestinationAmbiguous", () => {
    expect(ConnectResponseSchema.safeParse(connectAmbiguous).success).toBe(
      true,
    );
  });
});

describe("DisconnectResponseSchema", () => {
  it("parses NotConnected", () => {
    expect(
      DisconnectResponseSchema.safeParse(disconnectNotConnected).success,
    ).toBe(true);
  });

  it("parses Disconnecting", () => {
    expect(
      DisconnectResponseSchema.safeParse(disconnectDisconnecting).success,
    ).toBe(true);
  });
});

describe("ProbeResponseSchema", () => {
  it.each([
    ["Probing", probeProbing],
    ["Replaced", probeReplaced],
    ["AlreadyProbing", probeAlreadyProbing],
    ["UnableToProbe", probeUnable],
    ["NotReady", probeNotReady],
    ["DestinationNotFound", probeNotFound],
    ["DestinationAmbiguous", probeAmbiguous],
  ])("parses %s", (_name, fixture) => {
    expect(ProbeResponseSchema.safeParse(fixture).success).toBe(true);
  });
});

describe("UnprobeResponseSchema", () => {
  it.each([
    ["Closing", unprobeClosing],
    ["InUse", unprobeInUse],
    ["NotProbing", unprobeNotProbing],
  ])("parses %s", (_name, fixture) => {
    expect(UnprobeResponseSchema.safeParse(fixture).success).toBe(true);
  });
});

describe("QuickProbeResponseSchema", () => {
  it.each([
    ["Checking", quickProbeChecking],
    ["UnableToProbe", quickProbeUnable],
    ["AlreadyProbing", quickProbeAlreadyProbing],
    ["AlreadyChecking", quickProbeAlreadyChecking],
    ["NotReady", quickProbeNotReady],
    ["DestinationNotFound", quickProbeNotFound],
    ["DestinationAmbiguous", quickProbeAmbiguous],
  ])("parses %s", (_name, fixture) => {
    expect(QuickProbeResponseSchema.safeParse(fixture).success).toBe(true);
  });
});

describe("BalanceResponseSchema", () => {
  it("parses zero balance response", () => {
    const result = BalanceResponseSchema.safeParse(balanceResponse);
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(result.data.node).toBe(0n);
    expect(result.data.safe).toBe(0n);
    expect(result.data.channels_out).toBe(0n);
  });

  it("parses balance response with ideal_balance and funding_status", () => {
    const result = BalanceResponseSchema.safeParse(balanceResponseWithIssues);
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(typeof result.data.node).toBe("bigint");
    expect(result.data.ideal_balance).not.toBeNull();
    expect(typeof result.data.ideal_balance!.wxhopr).toBe("bigint");
    expect(typeof result.data.ideal_balance!.xdai).toBe("bigint");
    expect(result.data.ideal_balance!.wxhopr - result.data.safe)
      .toBeGreaterThan(0n);
    expect(result.data.funding_status).not.toBeNull();
    expect(result.data.funding_status!.traffic).toBe("Low");
    expect(typeof result.data.funding_status!.wxhopr_deficit).toBe("bigint");
  });

  it("parses balance response with capacity_allocations", () => {
    const result = BalanceResponseSchema.safeParse(balanceResponseWithCapacity);
    expect(result.success).toBe(true);
    if (!result.success) return;
    const caps = result.data.capacity_allocations;
    expect(caps).not.toBeNull();
    expect(typeof caps!.node.stake).toBe("bigint");
    expect(typeof caps!.safe.stake).toBe("bigint");
    const peers = Object.values(caps!.peer_allocations);
    expect(peers.length).toBeGreaterThan(0);
    expect(typeof peers[0].stake).toBe("bigint");
  });
});

describe("ServiceInfoSchema", () => {
  it("parses service info", () => {
    expect(ServiceInfoSchema.safeParse(serviceInfo).success).toBe(true);
  });
});

describe("DestinationSchema flag parsing", () => {
  // Wire-shaped input, as the daemon sends it, so the parse is exercised end to end.
  const destination = (flag: string | null) => ({
    id: "dest-1",
    meta: {
      name: null,
      location: "Somewhere",
      flag,
      description: null,
      other: {},
    },
    address: "0x1111111111111111111111111111111111111111",
    routing: 1,
    gnosis_vpn_server: "172.30.0.1:8000",
    wireguard_server: "172.30.0.1:51820",
    source: "Configured",
  });

  it("turns an unset flag into undefined", () => {
    const result = DestinationSchema.safeParse(destination(null));
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(result.data.meta.flag).toBeUndefined();
  });

  it("defaults the overrides an older daemon does not send", () => {
    const result = DestinationSchema.safeParse(destination("DE"));
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(result.data.overrides.configured_meta).toEqual({});
  });

  it("keeps a plain alpha-2 code", () => {
    const result = DestinationSchema.safeParse(destination("DE"));
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(result.data.meta.flag).toBe("de");
  });

  it("keeps a well-formed ISO 3166-2 subdivision code", () => {
    const result = DestinationSchema.safeParse(destination("GB-SCT"));
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(result.data.meta.flag).toBe("gb-sct");
  });

  // Regression: a malformed subdivision suffix used to fail the schema regex
  // outright, so .catch(undefined) dropped the flag entirely and Flag.tsx
  // never got the chance to fall back to the parent country's flag.
  it("preserves the parent country prefix for a malformed subdivision suffix", () => {
    const result = DestinationSchema.safeParse(destination("GB-foobar"));
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(result.data.meta.flag).toBe("gb-foobar");
  });
});
