import { describe, expect, it } from "vitest";
import {
  BalanceResponseSchema,
  ConnectResponseSchema,
  DisconnectResponseSchema,
  ServiceInfoSchema,
  StatusResponseSchema,
} from "./vpnService.ts";

// Fixtures are generated by `cargo test --test serialize_fixtures` in src-tauri.
// When library types change serde output, re-run that test to regenerate these files.
// If vitest then fails, update the Zod schemas to match the new wire format.
import statusNotRunning from "./fixtures/status_not_running.json";
import statusShutdown from "./fixtures/status_shutdown.json";
import statusWarmup from "./fixtures/status_warmup.json";
import statusRunning from "./fixtures/status_running.json";
import statusPreparingSafe from "./fixtures/status_preparing_safe.json";
import statusPreparingSafeWithRecommendation from "./fixtures/status_preparing_safe_with_recommendation.json";
import statusDeployingSafe from "./fixtures/status_deploying_safe.json";
import statusWithConnections from "./fixtures/status_with_connections.json";
import statusRouteHealthVariants from "./fixtures/status_route_health_variants.json";
import connectNotFound from "./fixtures/connect_destination_not_found.json";
import connectConnecting from "./fixtures/connect_connecting.json";
import connectAlreadyConnected from "./fixtures/connect_already_connected.json";
import connectWaiting from "./fixtures/connect_waiting.json";
import connectUnable from "./fixtures/connect_unable.json";
import disconnectNotConnected from "./fixtures/disconnect_not_connected.json";
import disconnectDisconnecting from "./fixtures/disconnect_disconnecting.json";
import balanceResponse from "./fixtures/balance_response.json";
import balanceResponseWithIssues from "./fixtures/balance_response_with_issues.json";
import balanceResponseWithCapacity from "./fixtures/balance_response_with_capacity.json";
import serviceInfo from "./fixtures/service_info.json";

describe("StatusResponseSchema", () => {
  it("parses NotRunning run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusNotRunning).success).toBe(true);
  });

  it("parses Shutdown run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusShutdown).success).toBe(true);
  });

  it("parses Warmup run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusWarmup).success).toBe(true);
  });

  it("parses Running run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusRunning).success).toBe(true);
  });

  it("parses PreparingSafe run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusPreparingSafe).success).toBe(
      true,
    );
  });

  it("parses PreparingSafe run_mode with balance_recommendation", () => {
    const result = StatusResponseSchema.safeParse(
      statusPreparingSafeWithRecommendation,
    );
    expect(result.success).toBe(true);
    if (!result.success) return;
    const mode = result.data.run_mode;
    expect(typeof mode).toBe("object");
    expect("PreparingSafe" in (mode as object)).toBe(true);
    const ps = (mode as {
      PreparingSafe: {
        node_xdai: bigint;
        node_wxhopr: bigint;
        balance_recommendation: { wxhopr: bigint; xdai: bigint } | null;
      };
    }).PreparingSafe;
    expect(typeof ps.node_xdai).toBe("bigint");
    expect(typeof ps.node_wxhopr).toBe("bigint");
    expect(ps.balance_recommendation).not.toBeNull();
    expect(typeof ps.balance_recommendation!.wxhopr).toBe("bigint");
    expect(typeof ps.balance_recommendation!.xdai).toBe("bigint");
  });

  it("parses DeployingSafe run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusDeployingSafe).success).toBe(
      true,
    );
  });

  it("parses ConnectedInfo and connection phase fields", () => {
    expect(StatusResponseSchema.safeParse(statusWithConnections).success).toBe(
      true,
    );
  });

  it("parses all RouteHealthState variants", () => {
    expect(
      StatusResponseSchema.safeParse(statusRouteHealthVariants).success,
    ).toBe(true);
  });
});

describe("ConnectResponseSchema", () => {
  it("parses DestinationNotFound", () => {
    expect(ConnectResponseSchema.safeParse(connectNotFound).success).toBe(true);
  });

  it("parses Connecting", () => {
    expect(ConnectResponseSchema.safeParse(connectConnecting).success).toBe(
      true,
    );
  });

  it("parses AlreadyConnected", () => {
    expect(ConnectResponseSchema.safeParse(connectAlreadyConnected).success)
      .toBe(
        true,
      );
  });

  it("parses WaitingToConnect", () => {
    expect(ConnectResponseSchema.safeParse(connectWaiting).success).toBe(true);
  });

  it("parses UnableToConnect", () => {
    expect(ConnectResponseSchema.safeParse(connectUnable).success).toBe(true);
  });
});

describe("DisconnectResponseSchema", () => {
  it("parses NotConnected", () => {
    expect(
      DisconnectResponseSchema.safeParse(disconnectNotConnected).success,
    ).toBe(true);
  });

  it("parses Disconnecting", () => {
    expect(
      DisconnectResponseSchema.safeParse(disconnectDisconnecting).success,
    ).toBe(true);
  });
});

describe("BalanceResponseSchema", () => {
  it("parses zero balance response", () => {
    const result = BalanceResponseSchema.safeParse(balanceResponse);
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(result.data.node).toBe(0n);
    expect(result.data.safe).toBe(0n);
    expect(result.data.channels_out).toBe(0n);
  });

  it("parses balance response with ideal_balance and funding_issues", () => {
    const result = BalanceResponseSchema.safeParse(balanceResponseWithIssues);
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(typeof result.data.node).toBe("bigint");
    expect(result.data.ideal_balance).not.toBeNull();
    expect(typeof result.data.ideal_balance!.wxhopr).toBe("bigint");
    expect(typeof result.data.ideal_balance!.xdai).toBe("bigint");
    expect(result.data.ideal_balance!.wxhopr - result.data.safe)
      .toBeGreaterThan(0n);
  });

  it("parses balance response with capacity_allocations", () => {
    const result = BalanceResponseSchema.safeParse(balanceResponseWithCapacity);
    expect(result.success).toBe(true);
    if (!result.success) return;
    expect(result.data.capacity_allocations).not.toBeNull();
    expect(result.data.capacity_allocations!.length).toBeGreaterThan(0);
    expect(typeof result.data.capacity_allocations![0].capacity.stake).toBe(
      "bigint",
    );
  });
});

describe("ServiceInfoSchema", () => {
  it("parses service info", () => {
    expect(ServiceInfoSchema.safeParse(serviceInfo).success).toBe(true);
  });
});
