import { describe, expect, it } from "vitest";
import {
  BalanceResponseSchema,
  ConnectResponseSchema,
  DisconnectResponseSchema,
  ServiceInfoSchema,
  StatusResponseSchema,
} from "./vpnService.ts";

// Fixtures are generated by `cargo test --test serialize_fixtures` in src-tauri.
// When library types change serde output, re-run that test to regenerate these files.
// If vitest then fails, update the Zod schemas to match the new wire format.
import statusNotRunning from "./fixtures/status_not_running.json";
import statusShutdown from "./fixtures/status_shutdown.json";
import statusWarmup from "./fixtures/status_warmup.json";
import statusRunning from "./fixtures/status_running.json";
import statusPreparingSafe from "./fixtures/status_preparing_safe.json";
import statusDeployingSafe from "./fixtures/status_deploying_safe.json";
import statusWithConnections from "./fixtures/status_with_connections.json";
import statusRouteHealthVariants from "./fixtures/status_route_health_variants.json";
import connectNotFound from "./fixtures/connect_destination_not_found.json";
import connectConnecting from "./fixtures/connect_connecting.json";
import connectAlreadyConnected from "./fixtures/connect_already_connected.json";
import connectWaiting from "./fixtures/connect_waiting.json";
import connectUnable from "./fixtures/connect_unable.json";
import disconnectNotConnected from "./fixtures/disconnect_not_connected.json";
import disconnectDisconnecting from "./fixtures/disconnect_disconnecting.json";
import balanceResponse from "./fixtures/balance_response.json";
import serviceInfo from "./fixtures/service_info.json";

describe("StatusResponseSchema", () => {
  it("parses NotRunning run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusNotRunning).success).toBe(true);
  });

  it("parses Shutdown run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusShutdown).success).toBe(true);
  });

  it("parses Warmup run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusWarmup).success).toBe(true);
  });

  it("parses Running run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusRunning).success).toBe(true);
  });

  it("parses PreparingSafe run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusPreparingSafe).success).toBe(
      true,
    );
  });

  it("parses DeployingSafe run_mode", () => {
    expect(StatusResponseSchema.safeParse(statusDeployingSafe).success).toBe(
      true,
    );
  });

  it("parses ConnectedInfo and connection phase fields", () => {
    expect(StatusResponseSchema.safeParse(statusWithConnections).success).toBe(
      true,
    );
  });

  it("parses all RouteHealthState variants", () => {
    expect(
      StatusResponseSchema.safeParse(statusRouteHealthVariants).success,
    ).toBe(true);
  });
});

describe("ConnectResponseSchema", () => {
  it("parses DestinationNotFound", () => {
    expect(ConnectResponseSchema.safeParse(connectNotFound).success).toBe(true);
  });

  it("parses Connecting", () => {
    expect(ConnectResponseSchema.safeParse(connectConnecting).success).toBe(
      true,
    );
  });

  it("parses AlreadyConnected", () => {
    expect(ConnectResponseSchema.safeParse(connectAlreadyConnected).success)
      .toBe(
        true,
      );
  });

  it("parses WaitingToConnect", () => {
    expect(ConnectResponseSchema.safeParse(connectWaiting).success).toBe(true);
  });

  it("parses UnableToConnect", () => {
    expect(ConnectResponseSchema.safeParse(connectUnable).success).toBe(true);
  });
});

describe("DisconnectResponseSchema", () => {
  it("parses NotConnected", () => {
    expect(
      DisconnectResponseSchema.safeParse(disconnectNotConnected).success,
    ).toBe(true);
  });

  it("parses Disconnecting", () => {
    expect(
      DisconnectResponseSchema.safeParse(disconnectDisconnecting).success,
    ).toBe(true);
  });
});

describe("BalanceResponseSchema", () => {
  it("parses balance response", () => {
    expect(BalanceResponseSchema.safeParse(balanceResponse).success).toBe(true);
  });
});

describe("ServiceInfoSchema", () => {
  it("parses service info", () => {
    expect(ServiceInfoSchema.safeParse(serviceInfo).success).toBe(true);
  });
});
