// Generated by scripts/generate-map.py from Natural Earth 110m admin-0 -- do not edit.
// See NOTICE.md for attribution.

export interface Region {
  /// Short English name, for a one-line label.
  readonly name: string;
  /// [minX, minY, maxX, maxY] in Mercator units, from the mainland only.
  readonly bbox: readonly [number, number, number, number];
  /// Where to drop a country-level marker; always on land.
  readonly point: readonly [number, number];
}

/// Keyed by ISO 3166-1 alpha-2, lowercased - the same codes Flag.tsx uses.
export const REGIONS: Readonly<Record<string, Region>> = {
  ae: {
    name: "United Arab Emirates",
    bbox: [643.28, 424.99, 656.66, 435.84],
    point: [650.59, 431.67],
  },
  af: {
    name: "Afghanistan",
    bbox: [668.13, 384.01, 708.77, 414.75],
    point: [683.69, 399.68],
  },
  al: {
    name: "Albania",
    bbox: [553.62, 368.63, 558.39, 379.94],
    point: [555.64, 374.36],
  },
  am: {
    name: "Armenia",
    bbox: [621.06, 374.01, 629.18, 383.1],
    point: [624.99, 377.76],
  },
  ao: {
    name: "Angola",
    bbox: [532.33, 516.32, 566.89, 550.64],
    point: [548.62, 534.57],
  },
  aq: {
    name: "Antarctica",
    bbox: [0.0, 728.74, 1000.0, 999.96],
    point: [559.82, 893.39],
  },
  ar: {
    name: "Argentina",
    bbox: [296.07, 562.17, 351.03, 671.27],
    point: [318.37, 608.57],
  },
  at: {
    name: "Austria",
    bbox: [526.33, 343.26, 547.17, 354.03],
    point: [539.12, 349.17],
  },
  au: {
    name: "Australia",
    bbox: [814.83, 529.81, 926.58, 617.95],
    point: [873.51, 574.88],
  },
  az: {
    name: "Azerbaijan",
    bbox: [624.92, 371.74, 639.98, 384.77],
    point: [632.44, 377.51],
  },
  ba: {
    name: "Bosnia and Herz.",
    bbox: [543.75, 358.8, 554.44, 368.77],
    point: [549.48, 362.89],
  },
  bd: {
    name: "Bangladesh",
    bbox: [744.68, 423.78, 757.42, 441.29],
    point: [750.73, 431.73],
  },
  be: {
    name: "Belgium",
    bbox: [506.98, 332.67, 517.1, 341.17],
    point: [512.72, 336.28],
  },
  bf: {
    name: "Burkina Faso",
    bbox: [484.8, 457.51, 506.05, 473.18],
    point: [495.07, 465.51],
  },
  bg: {
    name: "Bulgaria",
    bbox: [562.17, 362.71, 579.33, 374.06],
    point: [570.0, 368.34],
  },
  bi: {
    name: "Burundi",
    bbox: [580.62, 506.53, 585.42, 512.51],
    point: [583.09, 509.39],
  },
  bj: {
    name: "Benin",
    bbox: [502.15, 465.75, 510.55, 482.91],
    point: [506.49, 473.04],
  },
  bn: {
    name: "Brunei",
    bbox: [817.23, 484.84, 820.7, 488.86],
    point: [819.21, 486.96],
  },
  bo: {
    name: "Bolivia",
    bbox: [306.69, 527.25, 340.28, 565.29],
    point: [320.46, 547.34],
  },
  br: {
    name: "Brazil",
    bbox: [294.48, 485.41, 403.53, 599.76],
    point: [352.8, 531.34],
  },
  bs: {
    name: "Bahamas",
    bbox: [282.2, 427.6, 284.63, 432.17],
    point: [283.57, 429.75],
  },
  bt: {
    name: "Bhutan",
    bbox: [746.71, 417.99, 755.84, 422.93],
    point: [751.31, 420.72],
  },
  bw: {
    name: "Botswana",
    bbox: [555.27, 549.86, 581.76, 577.41],
    point: [566.02, 563.11],
  },
  by: {
    name: "Belarus",
    bbox: [564.44, 310.55, 590.82, 333.36],
    point: [577.75, 323.18],
  },
  bz: {
    name: "Belize",
    bbox: [252.14, 447.69, 255.26, 455.29],
    point: [253.6, 451.49],
  },
  ca: {
    name: "Canada",
    bbox: [108.34, 207.43, 345.32, 372.43],
    point: [212.57, 292.35],
  },
  cd: {
    name: "Dem. Rep. Congo",
    bbox: [533.84, 485.38, 586.59, 537.16],
    point: [565.52, 507.99],
  },
  cf: {
    name: "Central African Rep.",
    bbox: [540.17, 468.85, 576.04, 493.7],
    point: [556.6, 481.76],
  },
  cg: {
    name: "Congo",
    bbox: [530.82, 489.64, 551.26, 514.01],
    point: [542.04, 502.33],
  },
  ch: {
    name: "Switzerland",
    bbox: [516.73, 348.32, 529.01, 356.65],
    point: [522.55, 352.55],
  },
  ci: {
    name: "Côte d'Ivoire",
    bbox: [476.1, 470.6, 492.88, 487.94],
    point: [484.41, 478.93],
  },
  cl: {
    name: "Chile",
    bbox: [289.88, 549.62, 313.93, 678.24],
    point: [300.32, 619.96],
  },
  cm: {
    name: "Cameroon",
    bbox: [523.58, 463.98, 544.48, 495.2],
    point: [535.04, 484.2],
  },
  cn: {
    name: "China",
    bbox: [704.65, 323.62, 875.07, 442.44],
    point: [789.42, 387.03],
  },
  co: {
    name: "Colombia",
    bbox: [280.58, 465.18, 314.23, 511.95],
    point: [297.0, 489.02],
  },
  cr: {
    name: "Costa Rica",
    bbox: [261.27, 468.64, 270.71, 477.07],
    point: [266.18, 472.17],
  },
  cu: {
    name: "Cuba",
    bbox: [263.96, 433.75, 293.95, 443.71],
    point: [280.62, 438.4],
  },
  cy: {
    name: "Cyprus",
    bbox: [589.6, 395.51, 594.46, 397.55],
    point: [591.78, 396.41],
  },
  cz: {
    name: "Czechia",
    bbox: [534.0, 334.26, 552.37, 345.3],
    point: [542.58, 340.07],
  },
  de: {
    name: "Germany",
    bbox: [516.64, 316.38, 541.71, 350.49],
    point: [528.61, 333.69],
  },
  dj: {
    name: "Djibouti",
    bbox: [615.73, 464.43, 620.33, 469.46],
    point: [618.05, 467.06],
  },
  dk: {
    name: "Denmark",
    bbox: [522.47, 302.6, 530.31, 317.12],
    point: [525.87, 310.21],
  },
  do: {
    name: "Dominican Rep.",
    bbox: [300.15, 443.62, 310.23, 450.33],
    point: [304.27, 446.56],
  },
  dz: {
    name: "Algeria",
    bbox: [475.88, 388.82, 533.33, 446.06],
    point: [507.21, 417.51],
  },
  ec: {
    name: "Ecuador",
    bbox: [275.09, 496.16, 291.02, 513.79],
    point: [282.27, 504.05],
  },
  ee: {
    name: "Estonia",
    bbox: [564.83, 292.55, 578.14, 303.92],
    point: [571.73, 297.72],
  },
  eg: {
    name: "Egypt",
    bbox: [568.61, 407.45, 602.41, 437.33],
    point: [582.88, 423.29],
  },
  eh: {
    name: "W. Sahara",
    bbox: [452.6, 420.01, 475.93, 440.32],
    point: [466.35, 430.28],
  },
  er: {
    name: "Eritrea",
    bbox: [600.9, 449.16, 619.67, 465.13],
    point: [607.42, 456.59],
  },
  es: {
    name: "Spain",
    bbox: [473.91, 364.59, 508.44, 392.87],
    point: [489.96, 377.0],
  },
  et: {
    name: "Ethiopia",
    bbox: [591.54, 457.97, 632.75, 490.49],
    point: [609.85, 475.78],
  },
  fi: {
    name: "Finland",
    bbox: [557.35, 222.46, 587.54, 291.25],
    point: [572.89, 260.78],
  },
  fj: {
    name: "Fiji",
    bbox: [992.46, 548.92, 996.44, 551.69],
    point: [994.44, 550.35],
  },
  fk: {
    name: "Falkland Is.",
    bbox: [330.0, 665.66, 339.58, 671.04],
    point: [334.94, 668.4],
  },
  fr: {
    name: "France",
    bbox: [487.24, 334.12, 522.5, 369.93],
    point: [506.48, 352.83],
  },
  ga: {
    name: "Gabon",
    bbox: [524.44, 493.54, 540.07, 511.06],
    point: [532.47, 501.8],
  },
  gb: {
    name: "United Kingdom",
    bbox: [482.92, 297.83, 504.67, 339.32],
    point: [492.48, 320.71],
  },
  ge: {
    name: "Georgia",
    bbox: [610.99, 365.34, 629.55, 374.69],
    point: [620.76, 370.58],
  },
  gh: {
    name: "Ghana",
    bbox: [490.99, 468.98, 502.94, 486.9],
    point: [496.56, 477.88],
  },
  gl: {
    name: "Greenland",
    bbox: [296.4, 39.86, 466.09, 290.2],
    point: [385.46, 149.53],
  },
  gm: {
    name: "Gambia",
    bbox: [453.22, 461.07, 461.54, 463.2],
    point: [457.13, 462.22],
  },
  gn: {
    name: "Guinea",
    bbox: [457.97, 464.75, 478.24, 479.64],
    point: [469.27, 470.8],
  },
  gq: {
    name: "Eq. Guinea",
    bbox: [525.85, 493.65, 531.35, 497.19],
    point: [528.79, 495.43],
  },
  gr: {
    name: "Greece",
    bbox: [555.97, 371.86, 573.9, 391.27],
    point: [562.7, 380.81],
  },
  gt: {
    name: "Guatemala",
    bbox: [243.81, 449.68, 254.93, 461.48],
    point: [248.98, 455.81],
  },
  gw: {
    name: "Guinea-Bissau",
    bbox: [453.67, 464.63, 461.94, 469.14],
    point: [458.03, 466.35],
  },
  gy: {
    name: "Guyana",
    bbox: [329.42, 476.68, 342.95, 496.48],
    point: [336.19, 486.66],
  },
  hn: {
    name: "Honduras",
    bbox: [251.8, 454.95, 269.04, 463.62],
    point: [259.48, 458.35],
  },
  hr: {
    name: "Croatia",
    bbox: [537.94, 353.74, 553.86, 369.42],
    point: [542.73, 359.58],
  },
  ht: {
    name: "Haiti",
    bbox: [293.17, 443.53, 301.04, 449.07],
    point: [299.64, 446.51],
  },
  hu: {
    name: "Hungary",
    bbox: [545.01, 345.01, 563.08, 356.72],
    point: [553.79, 350.86],
  },
  id: {
    name: "Indonesia",
    bbox: [829.91, 495.43, 847.89, 515.79],
    point: [836.66, 505.88],
  },
  ie: {
    name: "Ireland",
    bbox: [472.29, 315.66, 483.24, 331.8],
    point: [477.75, 324.82],
  },
  il: {
    name: "Israel",
    bbox: [595.18, 401.88, 599.55, 414.17],
    point: [596.48, 407.72],
  },
  in: {
    name: "India",
    bbox: [689.38, 394.42, 770.56, 477.8],
    point: [721.14, 433.56],
  },
  iq: {
    name: "Iraq",
    bbox: [607.76, 387.89, 634.91, 415.45],
    point: [621.51, 402.44],
  },
  ir: {
    name: "Iran",
    bbox: [622.53, 379.62, 675.88, 428.0],
    point: [650.56, 403.75],
  },
  is: {
    name: "Iceland",
    bbox: [432.43, 249.91, 462.2, 269.86],
    point: [447.89, 259.56],
  },
  it: {
    name: "Italy",
    bbox: [518.75, 351.26, 551.33, 386.05],
    point: [533.75, 365.21],
  },
  jm: {
    name: "Jamaica",
    bbox: [282.4, 447.62, 288.33, 450.03],
    point: [285.21, 448.75],
  },
  jo: {
    name: "Jordan",
    bbox: [597.01, 401.54, 608.88, 415.14],
    point: [602.18, 408.5],
  },
  jp: {
    name: "Japan",
    bbox: [859.47, 373.53, 894.21, 409.26],
    point: [880.47, 392.28],
  },
  ke: {
    name: "Kenya",
    bbox: [594.15, 484.68, 616.26, 513.01],
    point: [604.98, 498.34],
  },
  kg: {
    name: "Kyrgyzstan",
    bbox: [692.96, 366.31, 722.94, 381.18],
    point: [707.32, 372.97],
  },
  kh: {
    name: "Cambodia",
    bbox: [784.3, 459.08, 798.93, 470.71],
    point: [791.32, 464.46],
  },
  kp: {
    name: "North Korea",
    bbox: [845.18, 367.5, 863.28, 386.89],
    point: [853.28, 377.94],
  },
  kr: {
    name: "South Korea",
    bbox: [850.33, 383.56, 859.63, 398.16],
    point: [855.06, 391.14],
  },
  kw: {
    name: "Kuwait",
    bbox: [629.36, 412.39, 634.49, 417.27],
    point: [632.22, 414.78],
  },
  kz: {
    name: "Kazakhstan",
    bbox: [629.07, 314.42, 742.67, 376.17],
    point: [686.99, 345.66],
  },
  la: {
    name: "Laos",
    bbox: [778.1, 435.93, 798.79, 461.06],
    point: [788.14, 447.75],
  },
  lb: {
    name: "Lebanon",
    bbox: [597.57, 397.3, 601.7, 402.5],
    point: [599.64, 399.75],
  },
  lk: {
    name: "Sri Lanka",
    bbox: [721.38, 472.58, 727.19, 483.39],
    point: [724.07, 478.54],
  },
  lr: {
    name: "Liberia",
    bbox: [468.23, 476.19, 479.06, 487.89],
    point: [473.86, 482.09],
  },
  ls: {
    name: "Lesotho",
    bbox: [575.0, 583.12, 581.46, 589.5],
    point: [578.25, 586.23],
  },
  lt: {
    name: "Lithuania",
    bbox: [558.49, 309.53, 573.86, 321.53],
    point: [566.32, 314.85],
  },
  lu: {
    name: "Luxembourg",
    bbox: [515.76, 338.59, 517.34, 341.54],
    point: [516.57, 340.15],
  },
  lv: {
    name: "Latvia",
    bbox: [558.49, 301.35, 578.27, 313.3],
    point: [568.97, 307.29],
  },
  ly: {
    name: "Libya",
    bbox: [525.89, 402.35, 569.9, 444.52],
    point: [549.85, 421.68],
  },
  ma: {
    name: "Morocco",
    bbox: [452.72, 393.51, 496.88, 439.06],
    point: [476.98, 412.29],
  },
  md: {
    name: "Moldova",
    bbox: [573.94, 345.67, 583.4, 357.8],
    point: [578.91, 350.84],
  },
  me: {
    name: "Montenegro",
    bbox: [551.25, 365.45, 556.5, 371.67],
    point: [553.57, 368.24],
  },
  mg: {
    name: "Madagascar",
    bbox: [620.15, 533.69, 640.21, 573.61],
    point: [629.65, 555.1],
  },
  mk: {
    name: "North Macedonia",
    bbox: [556.84, 370.02, 563.76, 375.5],
    point: [560.27, 372.67],
  },
  ml: {
    name: "Mali",
    bbox: [466.19, 428.32, 511.86, 471.81],
    point: [490.23, 451.0],
  },
  mm: {
    name: "Myanmar",
    bbox: [756.4, 417.87, 781.06, 472.27],
    point: [768.06, 439.89],
  },
  mn: {
    name: "Mongolia",
    bbox: [743.75, 330.1, 832.7, 372.72],
    point: [785.86, 351.9],
  },
  mr: {
    name: "Mauritania",
    bbox: [452.6, 420.82, 486.32, 458.95],
    point: [471.35, 442.4],
  },
  mw: {
    name: "Malawi",
    bbox: [590.8, 525.75, 599.37, 547.35],
    point: [594.99, 536.98],
  },
  mx: {
    name: "Mexico",
    bbox: [174.65, 403.72, 258.86, 459.17],
    point: [214.57, 430.75],
  },
  my: {
    name: "Malaysia",
    bbox: [804.62, 480.71, 831.06, 497.85],
    point: [818.55, 490.13],
  },
  mz: {
    name: "Mozambique",
    bbox: [583.83, 528.81, 613.27, 577.14],
    point: [598.44, 549.01],
  },
  na: {
    name: "Namibia",
    bbox: [532.59, 547.76, 569.68, 584.38],
    point: [547.68, 563.32],
  },
  nc: {
    name: "New Caledonia",
    bbox: [955.64, 557.03, 964.22, 563.87],
    point: [959.83, 560.47],
  },
  ne: {
    name: "Niger",
    bbox: [500.82, 432.9, 544.18, 467.38],
    point: [525.97, 450.88],
  },
  ng: {
    name: "Nigeria",
    bbox: [507.48, 461.1, 540.49, 488.21],
    point: [522.22, 473.29],
  },
  ni: {
    name: "Nicaragua",
    bbox: [256.48, 457.8, 269.04, 470.03],
    point: [263.83, 463.99],
  },
  nl: {
    name: "Netherlands",
    bbox: [509.21, 323.38, 519.7, 335.64],
    point: [515.32, 328.9],
  },
  no: {
    name: "Norway",
    bbox: [513.87, 213.89, 586.93, 300.78],
    point: [536.33, 256.99],
  },
  np: {
    name: "Nepal",
    bbox: [722.47, 411.22, 744.93, 423.93],
    point: [733.33, 418.13],
  },
  nz: {
    name: "New Zealand",
    bbox: [979.54, 602.05, 995.88, 627.62],
    point: [987.99, 616.28],
  },
  om: {
    name: "Oman",
    bbox: [644.44, 428.47, 666.13, 453.08],
    point: [655.87, 441.44],
  },
  pa: {
    name: "Panama",
    bbox: [269.54, 473.17, 285.44, 479.89],
    point: [277.47, 476.21],
  },
  pe: {
    name: "Peru",
    bbox: [273.86, 500.16, 309.26, 551.86],
    point: [293.41, 525.88],
  },
  pg: {
    name: "Papua New Guinea",
    bbox: [891.67, 507.23, 918.89, 529.76],
    point: [900.93, 518.53],
  },
  ph: {
    name: "Philippines",
    bbox: [833.01, 447.68, 844.95, 464.89],
    point: [837.61, 455.63],
  },
  pk: {
    name: "Pakistan",
    bbox: [669.1, 388.77, 716.22, 432.23],
    point: [693.07, 412.1],
  },
  pl: {
    name: "Poland",
    bbox: [539.1, 317.02, 566.75, 343.31],
    point: [553.6, 329.36],
  },
  pr: {
    name: "Puerto Rico",
    bbox: [313.22, 447.63, 317.8, 449.31],
    point: [315.34, 448.46],
  },
  ps: {
    name: "Palestine",
    bbox: [597.02, 404.34, 598.74, 408.2],
    point: [597.98, 406.28],
  },
  pt: {
    name: "Portugal",
    bbox: [473.54, 370.17, 482.25, 389.79],
    point: [477.63, 379.75],
  },
  py: {
    name: "Paraguay",
    bbox: [325.87, 554.78, 349.19, 579.65],
    point: [337.87, 566.58],
  },
  qa: {
    name: "Qatar",
    bbox: [640.96, 424.81, 643.35, 429.6],
    point: [642.18, 427.25],
  },
  ro: {
    name: "Romania",
    bbox: [556.17, 346.7, 582.3, 364.82],
    point: [569.27, 356.19],
  },
  rs: {
    name: "Serbia",
    bbox: [552.31, 355.07, 563.85, 370.3],
    point: [557.81, 362.63],
  },
  ru: {
    name: "Russia",
    bbox: [575.8, 145.44, 1000.0, 374.37],
    point: [780.64, 266.12],
  },
  rw: {
    name: "Rwanda",
    bbox: [580.62, 503.15, 585.6, 508.11],
    point: [583.11, 505.59],
  },
  sa: {
    name: "Saudi Arabia",
    bbox: [596.2, 405.57, 654.63, 453.96],
    point: [623.48, 430.44],
  },
  sb: {
    name: "Solomon Is.",
    bbox: [939.48, 520.39, 944.22, 523.81],
    point: [941.95, 522.02],
  },
  sd: {
    name: "Sudan",
    bbox: [560.94, 437.33, 606.69, 477.06],
    point: [583.0, 454.74],
  },
  se: {
    name: "Sweden",
    bbox: [530.63, 230.91, 566.4, 314.54],
    point: [546.8, 270.2],
  },
  si: {
    name: "Slovenia",
    bbox: [538.05, 352.33, 546.01, 357.94],
    point: [541.5, 355.25],
  },
  sk: {
    name: "Slovakia",
    bbox: [546.89, 340.99, 562.66, 348.61],
    point: [554.2, 344.56],
  },
  sl: {
    name: "Sierra Leone",
    bbox: [463.2, 471.95, 471.58, 481.11],
    point: [467.24, 476.21],
  },
  sn: {
    name: "Senegal",
    bbox: [451.04, 453.23, 468.14, 465.48],
    point: [459.69, 459.68],
  },
  so: {
    name: "Somalia",
    bbox: [613.84, 466.35, 642.04, 504.68],
    point: [627.06, 486.71],
  },
  sr: {
    name: "Suriname",
    bbox: [338.76, 483.23, 350.12, 494.95],
    point: [344.69, 488.54],
  },
  ss: {
    name: "S. Sudan",
    bbox: [566.35, 465.72, 598.05, 490.25],
    point: [583.88, 479.66],
  },
  sv: {
    name: "El Salvador",
    bbox: [249.73, 459.5, 256.32, 463.15],
    point: [253.13, 461.5],
  },
  sy: {
    name: "Syria",
    bbox: [599.17, 388.43, 617.64, 405.07],
    point: [607.1, 395.97],
  },
  sz: {
    name: "eSwatini",
    bbox: [585.21, 573.79, 589.09, 578.83],
    point: [587.21, 576.36],
  },
  td: {
    name: "Chad",
    bbox: [537.61, 433.08, 566.35, 479.33],
    point: [551.63, 456.59],
  },
  tf: {
    name: "Fr. S. Antarctic Lands",
    bbox: [690.89, 655.0, 696.0, 659.89],
    point: [693.14, 657.89],
  },
  tg: {
    name: "Togo",
    bbox: [499.86, 469.2, 505.18, 483.5],
    point: [502.77, 476.45],
  },
  th: {
    name: "Thailand",
    bbox: [770.49, 442.04, 793.3, 484.16],
    point: [780.58, 457.6],
  },
  tj: {
    name: "Tajikistan",
    bbox: [687.34, 375.07, 708.28, 390.14],
    point: [697.3, 383.61],
  },
  tl: {
    name: "Timor-Leste",
    bbox: [847.14, 523.06, 853.71, 526.21],
    point: [849.91, 524.45],
  },
  tm: {
    name: "Turkmenistan",
    bbox: [645.84, 368.39, 684.85, 395.18],
    point: [664.55, 381.66],
  },
  tn: {
    name: "Tunisia",
    bbox: [520.9, 388.01, 531.91, 411.59],
    point: [526.48, 398.72],
  },
  tr: {
    name: "Turkey",
    bbox: [572.7, 371.07, 624.43, 393.3],
    point: [598.33, 382.07],
  },
  tt: {
    name: "Trinidad and Tobago",
    bbox: [327.92, 469.57, 330.85, 472.08],
    point: [329.64, 470.87],
  },
  tw: {
    name: "Taiwan",
    bbox: [833.63, 427.33, 838.75, 437.42],
    point: [836.04, 432.06],
  },
  tz: {
    name: "Tanzania",
    bbox: [581.5, 502.64, 611.99, 532.79],
    point: [596.55, 517.47],
  },
  ua: {
    name: "Ukraine",
    bbox: [561.35, 328.8, 611.34, 358.57],
    point: [586.66, 342.51],
  },
  ug: {
    name: "Uganda",
    bbox: [582.17, 488.18, 597.32, 504.01],
    point: [589.88, 496.4],
  },
  us: {
    name: "United States of America",
    bbox: [153.65, 341.77, 313.99, 428.0],
    point: [224.36, 378.16],
  },
  uy: {
    name: "Uruguay",
    bbox: [337.7, 587.78, 352.2, 603.74],
    point: [344.44, 596.55],
  },
  uz: {
    name: "Uzbekistan",
    bbox: [655.36, 357.41, 702.93, 388.73],
    point: [675.34, 371.86],
  },
  ve: {
    name: "Venezuela",
    bbox: [296.38, 465.96, 334.0, 497.99],
    point: [316.2, 480.0],
  },
  vn: {
    name: "Vietnam",
    bbox: [783.81, 433.26, 803.71, 476.02],
    point: [796.77, 452.59],
  },
  vu: {
    name: "Vanuatu",
    bbox: [962.86, 541.08, 964.64, 544.28],
    point: [963.63, 542.79],
  },
  xk: {
    name: "Kosovo",
    bbox: [555.75, 366.41, 560.49, 371.79],
    point: [558.04, 369.03],
  },
  ye: {
    name: "Yemen",
    bbox: [618.35, 446.23, 647.52, 464.75],
    point: [632.07, 455.17],
  },
  za: {
    name: "South Africa",
    bbox: [545.4, 562.94, 591.19, 603.29],
    point: [569.62, 584.5],
  },
  zm: {
    name: "Zambia",
    bbox: [560.8, 522.96, 593.02, 550.73],
    point: [576.98, 537.64],
  },
  zw: {
    name: "Zimbabwe",
    bbox: [570.18, 543.61, 591.25, 563.49],
    point: [582.75, 553.57],
  },
};
