import { createSignal } from "solid-js";
import {
  createStore,
  reconcile,
  type Store as SolidStore,
} from "solid-js/store";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { z } from "zod";
import { logError } from "@src/utils/appLog.ts";

// ==========================================
// Zod Schemas & Inferred Types
// ==========================================
// Settings are owned by the Rust layer (src-tauri/src/settings.rs) and
// persisted there. This store is a passive mirror: setters send a patch via
// the `update_settings` command, state changes only arrive through the
// `settings-changed` event carrying a full snapshot, and `get_settings`
// hydrates late-joining windows.
// Fixtures for these schemas are generated by
// `cargo test --test serialize_fixtures` — see settingsStore.test.ts.

export const ChannelReleaseSchema = z.object({
  version: z.string(),
  published_at: z.string(),
  download_url: z.string(),
  size_bytes: z.string(),
  sha256: z.string(),
  artifact_signature: z.string(),
  release_notes: z.string(),
  min_os_version: z.string(),
  min_app_version: z.string(),
});
export type ChannelRelease = z.infer<typeof ChannelReleaseSchema>;

export const UpdateChannelSchema = z.enum([
  "stable",
  "snapshot",
  "experimental",
]);
export type UpdateChannel = z.infer<typeof UpdateChannelSchema>;

// The toolkit's `check-update` decision, `kind`-tagged by the Rust bridge. The
// last three never reach the frontend — `check_update` turns them into rejections.
export const CheckOutcomeSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("UpToDate"), current: z.string() }),
  z.object({
    kind: z.literal("Available"),
    current: z.string(),
    release: ChannelReleaseSchema,
  }),
  z.object({
    kind: z.literal("NoReleaseForChannel"),
    channel: UpdateChannelSchema,
  }),
  z.object({ kind: z.literal("VpnNotConnected") }),
  z.object({ kind: z.literal("IntegrityError"), error: z.string() }),
  z.object({ kind: z.literal("Error"), error: z.string() }),
]);
export type CheckOutcome = z.infer<typeof CheckOutcomeSchema>;

export const FlagDisplaySchema = z.enum(["none", "mono", "color"]);
export type FlagDisplay = z.infer<typeof FlagDisplaySchema>;

export const SettingsSchema = z.object({
  preferredLocation: z.string().nullable(),
  lastConnectedDestination: z.string().nullable(),
  connectOnStartup: z.boolean(),
  startMinimized: z.boolean(),
  updateCheck: z.boolean(),
  exitNodeSortOrder: z.enum(["best", "alpha"]),
  lastCheckedAt: z.number().nullable(),
  lastCheckOutcome: CheckOutcomeSchema.nullable(),
  channel: UpdateChannelSchema.nullable(),
  dismissedUpdateVersion: z.string().nullable(),
  installedVersion: z.string().nullable(),
  // Name is legacy — now drives whether the exit-health details panel
  // (chevron toggle) is expanded at all, not just its extra stat rows.
  showDetailedMetrics: z.boolean(),
  flagDisplay: FlagDisplaySchema,
});
export type SettingsState = z.infer<typeof SettingsSchema>;

// Shown until the first snapshot arrives; must match the Rust defaults.
const DEFAULT_SETTINGS: SettingsState = {
  preferredLocation: null,
  lastConnectedDestination: null,
  connectOnStartup: false,
  startMinimized: false,
  updateCheck: true,
  exitNodeSortOrder: "best",
  lastCheckedAt: null,
  lastCheckOutcome: null,
  channel: null,
  dismissedUpdateVersion: null,
  installedVersion: null,
  showDetailedMetrics: false,
  flagDisplay: "color",
};

type SettingsActions = {
  load: () => Promise<void>;
  /** Reactive: true once the first real snapshot replaced DEFAULT_SETTINGS. */
  hydrated: () => boolean;
  setPreferredLocation: (id: string | null) => Promise<void>;
  setLastConnectedDestination: (id: string | null) => Promise<void>;
  setConnectOnStartup: (enabled: boolean) => Promise<void>;
  setStartMinimized: (enabled: boolean) => Promise<void>;
  setUpdateCheck: (enabled: boolean) => Promise<void>;
  setExitNodeSortOrder: (order: "best" | "alpha") => Promise<void>;
  setUpdateCheckResult: (
    outcome: CheckOutcome,
    checkedAt: number,
  ) => Promise<void>;
  setChannel: (channel: UpdateChannel) => Promise<void>;
  syncInstalledVersion: (
    version: string,
    channel?: UpdateChannel,
  ) => Promise<void>;
  setDismissedUpdateVersion: (version: string | null) => Promise<void>;
  setShowDetailedMetrics: (show: boolean) => Promise<void>;
  setFlagDisplay: (display: FlagDisplay) => Promise<void>;
};

type SettingsStoreTuple = readonly [
  SolidStore<SettingsState>,
  SettingsActions,
  () => void,
];

export function createSettingsStore(): SettingsStoreTuple {
  const [state, setState] = createStore<SettingsState>({ ...DEFAULT_SETTINGS });
  const [hydrated, setHydrated] = createSignal(false);

  let loadPromise: Promise<void> | undefined;
  let unlistenChange: (() => void) | undefined;

  const applySnapshot = (payload: unknown) => {
    const parsed = SettingsSchema.safeParse(payload);
    if (!parsed.success) {
      const issues = parsed.error.issues
        .map((i) => `${i.path.join(".") || "root"}: ${i.message}`)
        .join("; ");
      logError(`Invalid settings snapshot: ${issues}`);
      return;
    }
    setState(reconcile(parsed.data));
  };

  // Subscribe before hydrating so no change is missed; a change event
  // arriving mid-hydration is buffered and re-applied afterwards, since it
  // is newer than the get_settings snapshot.
  const hydrate = async (): Promise<void> => {
    let buffered: unknown;
    let hydrating = true;
    try {
      unlistenChange = await listen<unknown>(
        "settings-changed",
        ({ payload }) => {
          if (hydrating) {
            buffered = payload;
            return;
          }
          applySnapshot(payload);
        },
      );
      applySnapshot(await invoke<unknown>("get_settings"));
      setHydrated(true);
    } catch (e) {
      logError(`Failed to load settings: ${e}`);
    } finally {
      hydrating = false;
    }
    if (buffered !== undefined) applySnapshot(buffered);
  };

  // The only write path. State is never set here — the Rust layer applies
  // the patch and broadcasts the resulting snapshot to every window.
  const patch = async (entries: Partial<SettingsState>): Promise<void> => {
    try {
      await invoke("update_settings", { patch: entries });
    } catch (e) {
      logError(`Failed to update settings ${JSON.stringify(entries)}: ${e}`);
    }
  };

  const actions: SettingsActions = {
    load: () => {
      loadPromise ??= hydrate();
      return loadPromise;
    },
    hydrated,
    setPreferredLocation: (id) => patch({ preferredLocation: id }),
    setLastConnectedDestination: (id) =>
      patch({ lastConnectedDestination: id }),
    setConnectOnStartup: (enabled) => patch({ connectOnStartup: enabled }),
    setStartMinimized: (enabled) => patch({ startMinimized: enabled }),
    setUpdateCheck: (enabled) => patch({ updateCheck: enabled }),
    setExitNodeSortOrder: (order) => patch({ exitNodeSortOrder: order }),
    setUpdateCheckResult: (outcome, checkedAt) =>
      patch({ lastCheckOutcome: outcome, lastCheckedAt: checkedAt }),
    setChannel: (channel) => patch({ channel }),
    // Marker and channel land in one patch so a crash between them cannot
    // record the new version while keeping the stale channel.
    syncInstalledVersion: (version, channel) =>
      patch({
        installedVersion: version,
        ...(channel ? { channel } : {}),
      }),
    setDismissedUpdateVersion: (version) =>
      patch({ dismissedUpdateVersion: version }),
    setShowDetailedMetrics: (show) => patch({ showDetailedMetrics: show }),
    setFlagDisplay: (display) => patch({ flagDisplay: display }),
  } as const;

  const dispose = () => {
    unlistenChange?.();
  };

  return [state, actions, dispose] as const;
}

const settingsStore = createSettingsStore();

export function useSettingsStore(): SettingsStoreTuple {
  return settingsStore;
}
