import {
  createStore,
  reconcile,
  type Store as SolidStore,
} from "solid-js/store";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { z } from "zod";

// ==========================================
// Zod Schemas & Inferred Types
// ==========================================
// Settings are owned by the Rust layer (src-tauri/src/settings.rs) and
// persisted there. This store is a passive mirror: setters send a patch via
// the `update_settings` command, state changes only arrive through the
// `settings-changed` event carrying a full snapshot, and `get_settings`
// hydrates late-joining windows.
// Fixtures for these schemas are generated by
// `cargo test --test serialize_fixtures` — see settingsStore.test.ts.

export const ChannelReleaseSchema = z.object({
  version: z.string(),
  published_at: z.string(),
  download_url: z.string(),
  size_bytes: z.string(),
  sha256: z.string(),
  artifact_signature: z.string(),
  release_notes: z.string(),
  min_os_version: z.string(),
  min_app_version: z.string(),
});
export type ChannelRelease = z.infer<typeof ChannelReleaseSchema>;

export const UpdateManifestSchema = z.object({
  schema_version: z.number(),
  generated_at: z.string(),
  channels: z.object({
    stable: ChannelReleaseSchema.nullable(),
    snapshot: ChannelReleaseSchema.nullable(),
  }),
});
export type UpdateManifest = z.infer<typeof UpdateManifestSchema>;

export const UpdateChannelSchema = z.enum(["stable", "snapshot"]);
export type UpdateChannel = z.infer<typeof UpdateChannelSchema>;

export const FlagDisplaySchema = z.enum(["none", "mono", "color"]);
export type FlagDisplay = z.infer<typeof FlagDisplaySchema>;

export const SettingsSchema = z.object({
  preferredLocation: z.string().nullable(),
  connectOnStartup: z.boolean(),
  startMinimized: z.boolean(),
  updateCheck: z.boolean(),
  exitNodeSortOrder: z.enum(["latency", "alpha"]),
  lastCheckedAt: z.number().nullable(),
  updateManifest: UpdateManifestSchema.nullable(),
  channel: UpdateChannelSchema.nullable(),
  dismissedUpdateVersion: z.string().nullable(),
  showDetailedMetrics: z.boolean(),
  flagDisplay: FlagDisplaySchema,
});
export type SettingsState = z.infer<typeof SettingsSchema>;

// Shown until the first snapshot arrives; must match the Rust defaults.
const DEFAULT_SETTINGS: SettingsState = {
  preferredLocation: null,
  connectOnStartup: false,
  startMinimized: false,
  updateCheck: false,
  exitNodeSortOrder: "latency",
  lastCheckedAt: null,
  updateManifest: null,
  channel: null,
  dismissedUpdateVersion: null,
  showDetailedMetrics: false,
  flagDisplay: "color",
};

type SettingsActions = {
  load: () => Promise<void>;
  setPreferredLocation: (id: string | null) => Promise<void>;
  setConnectOnStartup: (enabled: boolean) => Promise<void>;
  setStartMinimized: (enabled: boolean) => Promise<void>;
  setUpdateCheck: (enabled: boolean) => Promise<void>;
  setExitNodeSortOrder: (order: "latency" | "alpha") => Promise<void>;
  setUpdateCheckResult: (
    manifest: UpdateManifest,
    checkedAt: number,
  ) => Promise<void>;
  setChannel: (channel: UpdateChannel) => Promise<void>;
  setDismissedUpdateVersion: (version: string | null) => Promise<void>;
  setShowDetailedMetrics: (show: boolean) => Promise<void>;
  setFlagDisplay: (display: FlagDisplay) => Promise<void>;
};

type SettingsStoreTuple = readonly [
  SolidStore<SettingsState>,
  SettingsActions,
  () => void,
];

export function createSettingsStore(): SettingsStoreTuple {
  const [state, setState] = createStore<SettingsState>({ ...DEFAULT_SETTINGS });

  let loadPromise: Promise<void> | undefined;
  let unlistenChange: (() => void) | undefined;

  const applySnapshot = (payload: unknown) => {
    const parsed = SettingsSchema.safeParse(payload);
    if (!parsed.success) {
      const issues = parsed.error.issues
        .map((i) => `${i.path.join(".") || "root"}: ${i.message}`)
        .join("; ");
      console.error(`Invalid settings snapshot: ${issues}`);
      return;
    }
    setState(reconcile(parsed.data));
  };

  // Subscribe before hydrating so no change is missed; a change event
  // arriving mid-hydration is buffered and re-applied afterwards, since it
  // is newer than the get_settings snapshot.
  const hydrate = async (): Promise<void> => {
    let buffered: unknown;
    let hydrating = true;
    try {
      unlistenChange = await listen<unknown>(
        "settings-changed",
        ({ payload }) => {
          if (hydrating) {
            buffered = payload;
            return;
          }
          applySnapshot(payload);
        },
      );
      applySnapshot(await invoke<unknown>("get_settings"));
    } catch (e) {
      console.error("Failed to load settings:", e);
    } finally {
      hydrating = false;
    }
    if (buffered !== undefined) applySnapshot(buffered);
  };

  // The only write path. State is never set here — the Rust layer applies
  // the patch and broadcasts the resulting snapshot to every window.
  const patch = async (entries: Partial<SettingsState>): Promise<void> => {
    try {
      await invoke("update_settings", { patch: entries });
    } catch (e) {
      console.error("Failed to update settings", Object.keys(entries), e);
    }
  };

  const actions: SettingsActions = {
    load: () => {
      loadPromise ??= hydrate();
      return loadPromise;
    },
    setPreferredLocation: (id) => patch({ preferredLocation: id }),
    setConnectOnStartup: (enabled) => patch({ connectOnStartup: enabled }),
    setStartMinimized: (enabled) => patch({ startMinimized: enabled }),
    setUpdateCheck: (enabled) => patch({ updateCheck: enabled }),
    setExitNodeSortOrder: (order) => patch({ exitNodeSortOrder: order }),
    setUpdateCheckResult: (manifest, checkedAt) =>
      patch({ updateManifest: manifest, lastCheckedAt: checkedAt }),
    setChannel: (channel) => patch({ channel }),
    setDismissedUpdateVersion: (version) =>
      patch({ dismissedUpdateVersion: version }),
    setShowDetailedMetrics: (show) => patch({ showDetailedMetrics: show }),
    setFlagDisplay: (display) => patch({ flagDisplay: display }),
  } as const;

  const dispose = () => {
    unlistenChange?.();
  };

  return [state, actions, dispose] as const;
}

const settingsStore = createSettingsStore();

export function useSettingsStore(): SettingsStoreTuple {
  return settingsStore;
}
