import { beforeEach, describe, expect, it, vi } from "vitest";

// Fixtures are generated by `cargo test --test serialize_fixtures` in
// src-tauri. When the Rust Settings type changes serde output, re-run that
// test to regenerate these files. If vitest then fails, update the Zod
// schemas to match the new wire format.
import settingsDefault from "../services/fixtures/settings_default.json";
import settingsFull from "../services/fixtures/settings_full.json";

const { invokeMock, listenMock } = vi.hoisted(() => ({
  invokeMock: vi.fn(),
  listenMock: vi.fn(),
}));

vi.mock("@tauri-apps/api/core", () => ({ invoke: invokeMock }));
vi.mock("@tauri-apps/api/event", () => ({ listen: listenMock }));

type ChangeHandler = (event: { payload: unknown }) => void;

// The module holds a singleton store, so every test imports a fresh copy.
async function freshStore() {
  const mod = await import("./settingsStore.ts");
  return mod.createSettingsStore();
}

let changeHandler: ChangeHandler | undefined;

function mockBackend(snapshot: unknown) {
  listenMock.mockImplementation((_event: string, cb: ChangeHandler) => {
    changeHandler = cb;
    return Promise.resolve(() => {
      changeHandler = undefined;
    });
  });
  invokeMock.mockImplementation((cmd: string) => {
    if (cmd === "get_settings") return Promise.resolve(snapshot);
    return Promise.resolve(null);
  });
}

function fireChange(payload: unknown) {
  if (!changeHandler) throw new Error("no settings-changed listener");
  changeHandler({ payload });
}

beforeEach(() => {
  vi.resetModules();
  invokeMock.mockReset();
  listenMock.mockReset();
  changeHandler = undefined;
});

describe("SettingsSchema fixtures", () => {
  it("parses settings_default.json", async () => {
    const { SettingsSchema } = await import("./settingsStore.ts");
    expect(SettingsSchema.safeParse(settingsDefault).success).toBe(true);
  });

  it("parses settings_full.json", async () => {
    const { SettingsSchema } = await import("./settingsStore.ts");
    expect(SettingsSchema.safeParse(settingsFull).success).toBe(true);
  });
});

describe("settingsStore", () => {
  it("hydrates from get_settings", async () => {
    mockBackend(settingsFull);
    const [state, actions] = await freshStore();

    await actions.load();

    expect(state.preferredLocation).toBe("exit-1");
    expect(state.exitNodeSortOrder).toBe("alpha");
    expect(state.channel).toBe("snapshot");
    expect(state.updateManifest?.channels.stable?.version).toBe("0.29.0");
  });

  it("applies settings-changed events including nulls", async () => {
    mockBackend(settingsFull);
    const [state, actions] = await freshStore();
    await actions.load();

    fireChange({ ...settingsFull, preferredLocation: null, channel: null });

    expect(state.preferredLocation).toBe(null);
    expect(state.channel).toBe(null);
  });

  it("ignores invalid snapshots and keeps current state", async () => {
    mockBackend(settingsFull);
    const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
    const [state, actions] = await freshStore();
    await actions.load();

    fireChange({ ...settingsFull, exitNodeSortOrder: "bogus" });

    expect(state.exitNodeSortOrder).toBe("alpha");
    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining("Invalid settings snapshot"),
    );
    errorSpy.mockRestore();
  });

  it("setters send a patch and never touch state directly", async () => {
    mockBackend(settingsDefault);
    const [state, actions] = await freshStore();
    await actions.load();

    await actions.setConnectOnStartup(true);

    expect(invokeMock).toHaveBeenCalledWith("update_settings", {
      patch: { connectOnStartup: true },
    });
    // state only changes once the snapshot event arrives
    expect(state.connectOnStartup).toBe(false);
    fireChange({ ...settingsDefault, connectOnStartup: true });
    expect(state.connectOnStartup).toBe(true);
  });

  it("swallows update_settings failures without touching state", async () => {
    mockBackend(settingsDefault);
    const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
    const [state, actions] = await freshStore();
    await actions.load();
    invokeMock.mockRejectedValueOnce(new Error("disk full"));

    await expect(actions.setUpdateCheck(true)).resolves.toBeUndefined();

    expect(state.updateCheck).toBe(false);
    expect(errorSpy).toHaveBeenCalled();
    errorSpy.mockRestore();
  });

  it("replays a change event that raced the hydration snapshot", async () => {
    // get_settings resolves late with a stale snapshot; a newer
    // settings-changed event arrives in between and must win.
    let resolveGet: (v: unknown) => void = () => {};
    listenMock.mockImplementation((_event: string, cb: ChangeHandler) => {
      changeHandler = cb;
      return Promise.resolve(() => {});
    });
    invokeMock.mockImplementation(() =>
      new Promise((resolve) => {
        resolveGet = resolve;
      })
    );
    const [state, actions] = await freshStore();

    const loading = actions.load();
    // wait for the listener registration before firing
    await vi.waitFor(() => {
      if (!changeHandler) throw new Error("listener not ready");
    });
    fireChange({ ...settingsDefault, showDetailedMetrics: true });
    resolveGet(settingsDefault);
    await loading;

    expect(state.showDetailedMetrics).toBe(true);
  });

  it("load() is idempotent", async () => {
    mockBackend(settingsDefault);
    const [, actions] = await freshStore();

    await Promise.all([actions.load(), actions.load()]);
    await actions.load();

    expect(listenMock).toHaveBeenCalledTimes(1);
    expect(invokeMock).toHaveBeenCalledTimes(1);
  });
});
