name: Build
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.ref }}-build
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  build-binaries:
    strategy:
      matrix:
        include:
          - architecture: x86_64-linux
            runner: depot-ubuntu-22.04-4 # Depot Ubuntu 22.04, 4 CPUs, 16 GB RAM
            required_label: ""
          - architecture: aarch64-linux
            runner: depot-ubuntu-22.04-arm-4 # Depot Ubuntu 22.04 ARM, 4 CPUs, 16 GB RAM
            required_label: "binary:aarch64-linux"
          - architecture: aarch64-darwin
            runner: depot-macos-15 # Depot Apple Silicon M2, 8 CPUs, 24 GB RAM, 400 GB SSD
            required_label: "binary:aarch64-darwin"
    name: Binary ${{ matrix.architecture }}
    uses: ./.github/workflows/build-binaries.yaml
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      architecture: ${{ matrix.architecture }}
      runner: ${{ matrix.runner }}
      version_type: "commit"
      enabled: ${{ matrix.required_label == '' || contains(github.event.pull_request.labels.*.name, matrix.required_label) }}
    secrets: inherit
  checks:
    name: Checks
    runs-on: depot-ubuntu-22.04-4
    steps:
      - name: Run checks
        uses: hoprnet/hopr-workflows/actions/nix-action@nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
          cachix_cache_name: gnosis-vpn-app
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          command: nix flake check -L --show-trace --max-jobs 1
