#################################################################################
# Pipeline to build binaries
#################################################################################
name: Create binaries
on:
  workflow_call:
    inputs:
      source_branch:
        required: true
        type: string
      version_type:
        required: true
        type: string
      architecture:
        required: true
        type: string
      runner:
        required: true
        type: string
      enabled:
        required: false
        type: boolean
        default: true
jobs:
  binary:
    permissions:
      contents: read
      pull-requests: read
    if: inputs.enabled
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 90
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          disable-sudo: false
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          ref: ${{ inputs.source_branch }}
      - name: Setup Nix
        uses: hoprnet/hopr-workflows/actions/setup-nix@setup-nix-v1
        with:
          cachix_cache_name: gnosis-vpn-app
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Updates build version
        id: version
        uses: hoprnet/hopr-workflows/actions/set-build-version@set-build-version-v2
        with:
          file: src-tauri/Cargo.toml
          version_type: ${{ inputs.version_type }}
          architecture: ${{ inputs.architecture }}
      - name: Set environment variables
        id: vars
        run: |
          declare architecture rust_toolchain_target tauri_args
            architecture=${{ inputs.architecture }}
          if [[ "${architecture}" =~ "-darwin" ]]; then
            rust_toolchain_target="${architecture/-darwin/}-apple-darwin"
            tauri_args="--target ${rust_toolchain_target}"
          elif [[ "${architecture}" == "aarch64-linux" ]]; then
            rust_toolchain_target="aarch64-unknown-linux-gnu"
            tauri_args="--bundles deb"
          else
            rust_toolchain_target="x86_64-unknown-linux-gnu"
            tauri_args="--bundles deb"
          fi

          echo "Invocation parameters:"
          echo "rust_toolchain_target=${rust_toolchain_target}" | tee -a $GITHUB_OUTPUT
          echo "tauri_args=${tauri_args}" | tee -a $GITHUB_OUTPUT
      - name: Install Rust toolchain (stable) + targets
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ steps.vars.outputs.rust_toolchain_target }}
      - name: Rust cache
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
        with:
          workspaces: |
            ./src-tauri -> target
      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x
      - name: install ubuntu dependencies
        if: ${{ endsWith(inputs.architecture, '-linux') }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install frontend dependencies
        run: deno install
      - name: Import Apple Developer Certificate
        if: ${{ endsWith(inputs.architecture, '-darwin') }}
        id: certificate
        shell: bash
        env:
          APPLE_CERTIFICATE_DEVELOPER_P12_BASE64: ${{ secrets.APPLE_CERTIFICATE_DEVELOPER_P12_BASE64 }}
          APPLE_CERTIFICATE_DEVELOPER_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_DEVELOPER_PASSWORD }}
        run: |
          set -euo pipefail
          echo $APPLE_CERTIFICATE_DEVELOPER_P12_BASE64 | base64 --decode > gnosisvpn-developer.p12
          keychain_pass=$(openssl rand -base64 24)
          security create-keychain -p "$keychain_pass" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$keychain_pass" build.keychain
          security set-keychain-settings -lut 21600 -u build.keychain
          security import gnosisvpn-developer.p12 -k build.keychain -P "$APPLE_CERTIFICATE_DEVELOPER_PASSWORD" -T /usr/bin/codesign
          echo "Certificate imported."
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$keychain_pass" build.keychain
          signing_identity=$(security find-identity -v -p codesigning build.keychain | awk -F'"' '{print $2}')
          echo "Apple signing identity: $signing_identity"
          echo "signing_identity=${signing_identity}" | tee -a $GITHUB_OUTPUT
      - name: Build tauri mac artifact
        if: ${{ endsWith(inputs.architecture, '-darwin') }}
        id: build-tauri-mac
        uses: tauri-apps/tauri-action@84b9d35b5fc46c1e45415bdb6144030364f7ebc5 # v0.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE_DEVELOPER_P12_BASE64 }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_DEVELOPER_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ steps.certificate.outputs.signing_identity }}
          # https://github.com/tauri-apps/tauri-action/issues/1294
          TAURI_BUNDLER_DMG_IGNORE_CI: "false"
        with:
          tauriScript: "deno task tauri"
          args: ${{ steps.vars.outputs.tauri_args }}
      - name: Build tauri linux artifact
        if: ${{ endsWith(inputs.architecture, '-linux') }}
        id: build-tauri-linux
        uses: tauri-apps/tauri-action@84b9d35b5fc46c1e45415bdb6144030364f7ebc5 # v0.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: "deno task tauri"
          args: ${{ steps.vars.outputs.tauri_args }}
      - name: Post-process artifacts
        id: path
        run: |
          mkdir -p artifacts
          artifact_path="${{ github.workspace }}/artifacts"
          binary_name="gnosis_vpn-app-${{ inputs.architecture }}"
          if [[ "${{ inputs.architecture }}" =~ "-darwin" ]]; then
            echo "Filtering DMG artifact for architecture ${{ inputs.architecture }}"
            artifact_json='${{ steps.build-tauri-mac.outputs.artifactPaths }}'
            dmg_path=$(echo "$artifact_json" | jq -r '.[] | select(endswith(".dmg"))')
            mv "${dmg_path}" "${artifact_path}/${binary_name}.dmg"
            shasum -a 256 "${artifact_path}/${binary_name}.dmg" > "${artifact_path}/${binary_name}.dmg.sha256"
          else
            echo "Filtering DEB artifact for architecture ${{ inputs.architecture }}"
            artifact_json='${{ steps.build-tauri-linux.outputs.artifactPaths }}'
            deb_path=$(echo "$artifact_json" | jq -r '.[] | select(endswith(".deb"))')
            mv "${deb_path}" "${artifact_path}/${binary_name}.deb"
            shasum -a 256 "${artifact_path}/${binary_name}.deb" > "${artifact_path}/${binary_name}.deb.sha256"
          fi
      - name: Setup GCP
        if: steps.version.outputs.publish_artifact_registry == 'true'
        uses: hoprnet/hopr-workflows/actions/setup-gcp@setup-gcp-v3
        with:
          google_credentials: ${{ secrets.GCP_SA_GITHUB_ACTIONS }}
          install_sdk: "true"
      - name: Publish ${{ inputs.architecture }} into Google Artifact registry
        if: steps.version.outputs.publish_artifact_registry == 'true'
        uses: hoprnet/hopr-workflows/actions/upload-artifact-registry@upload-artifact-registry-v2
        with:
          source: ${{ github.workspace }}/artifacts
          package: gnosis_vpn-app
          version: ${{ steps.version.outputs.build_version }}
      - name: Upload ${{ inputs.architecture }} binaries
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: gnosis_vpn-app-${{ inputs.architecture }}-binaries
          path: ${{ github.workspace }}/artifacts
